name: Testing suite

on:
  schedule:
    - cron: "0 11 * * 1"
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup gfortran
          run: |
            sudo apt-get update
            sudo apt-get install  \
              gfortran            \
              openmpi-bin         \
              libopenmpi-dev
        - name: Setup FPM
          uses: fortran-lang/setup-fpm@v5
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Build SsTC_driver
          run: |
            fpm run
        - name: Test SsTC_driver (MPI singleton)
          run: |
            fpm test -compiler mpifort --runner-args=" -np 1"
        - name: Test SsTC_driver (2 MPI processes)
          run: |
            fpm test -compiler mpifort --runner-args=" -np 2"
